

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: booksapp-laravel-prod
    container_name: booksapp-laravel-prod
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - booksapp

  nginx:
    image: nginx:alpine
    container_name: booksapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      
    depends_on:
      - app
    networks:
      - booksapp

networks:
  booksapp:
    driver: bridge
